version: "3"
services:
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"

  backend:
    image: umamibook-backend
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/src:/app/src
    ports:
      - "5000:5000"
    expose:
      - 5000

  frontend:
    image: umamibook-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    ports:
      - "3000:3000"
    expose:
      - 3000